<script src="{{ asset('asset/public/jquery-3.7.1.min.js') }}"></script>
<script src="asset/public/vendors/popper/popper.min.js"></script>
<script src="asset/public/vendors/bootstrap/bootstrap.min.js"></script>
<script src="asset/public/vendors/anchorjs/anchor.min.js"></script>
<script src="asset/public/vendors/is/is.min.js"></script>
<script src="asset/public/vendors/fontawesome/all.min.js"></script>
<script src="asset/public/vendors/lodash/lodash.min.js"></script>
<script src="asset/public/vendors/list.js/list.min.js"></script>
<script src="asset/public/assets/js/theme.js"></script>
